{{- if and .Values.internalTLS.enabled (eq .Values.internalTLS.certSource "auto") }}
{{- $ca := genCA "base-internal-ca" 365 }}
{{- $agCN := (include "base.apigateway" .) }}
{{- $agCrt := genSignedCert $agCN (list "127.0.0.1") (list "localhost" $agCN) 365 $ca }}
{{- $mgmtCN := (include "base.mgmt" .) }}
{{- $mgmtCrt := genSignedCert $mgmtCN (list "127.0.0.1") (list "localhost" $mgmtCN) 365 $ca }}
{{- $consoleCN := (include "base.console" .) }}
{{- $consoleCrt := genSignedCert $consoleCN (list "127.0.0.1") (list "localhost" $consoleCN) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "base.internalTLS.apigateway.secretName" . }}"
  labels:
    {{- include "base.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $agCrt.Cert | b64enc | quote }}
  tls.key: {{ $agCrt.Key | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "base.internalTLS.mgmt.secretName" . }}"
  labels:
    {{- include "base.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $mgmtCrt.Cert | b64enc | quote }}
  tls.key: {{ $mgmtCrt.Key | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "base.internalTLS.console.secretName" . }}"
  labels:
    {{- include "base.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $consoleCrt.Cert | b64enc | quote }}
  tls.key: {{ $consoleCrt.Key | b64enc | quote }}
---
{{- end }}
