apiVersion: v1
kind: Service
metadata:
{{- if or (eq .Values.expose.type "clusterIP") (eq .Values.expose.type "ingress") }}
{{- $clusterIP := .Values.expose.clusterIP }}
  name: {{ include "base.apiGatewayBase" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
  {{- with $clusterIP.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: {{ ternary "https" "http" .Values.apiGatewayBase.tls.enabled }}
      port: {{ default (include "base.apiGatewayBase.httpPort" .) $clusterIP.ports.apiGatewayBaseHttp }}
      targetPort: {{ template "base.apiGatewayBase.httpPort" . }}
    - name: stats
      port: {{ default (include "base.apiGatewayBase.statsPort" .) $clusterIP.ports.apiGatewayBaseStats }}
      targetPort: {{ template "base.apiGatewayBase.statsPort" . }}
    - name: metrics
      port: {{ default (include "base.apiGatewayBase.metricsPort" .) $clusterIP.ports.apiGatewayBaseMetrics }}
      targetPort: {{ template "base.apiGatewayBase.metricsPort" . }}
{{- else if eq .Values.expose.type "nodePort" }}
{{- $nodePort := .Values.expose.nodePort }}
  name: {{ include "base.apiGatewayBase" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
  {{- with $nodePort.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: NodePort
  ports:
    - name: {{ ternary "https" "http" .Values.apiGatewayBase.tls.enabled }}
      port: {{ default (include "base.apiGatewayBase.httpPort" .) $nodePort.ports.apiGatewayBaseHttp.port }}
      targetPort: {{ template "base.apiGatewayBase.httpPort" . }}
      {{- if and (ge ($nodePort.ports.apiGatewayBaseHttp.nodePort | int) (30000 | int)) (le ($nodePort.ports.apiGatewayBaseHttp.nodePort | int) (32767 | int)) }}
      nodePort: {{ $nodePort.ports.apiGatewayBaseHttp.nodePort }}
      {{- end }}
    - name: stats
      port: {{ default (include "base.apiGatewayBase.statsPort" .) $nodePort.ports.apiGatewayBaseStats.port }}
      targetPort: {{ template "base.apiGatewayBase.statsPort" . }}
      {{- if and (ge ($nodePort.ports.apiGatewayBaseStats.nodePort | int) (30000 | int)) (le ($nodePort.ports.apiGatewayBaseStats.nodePort | int) (32767 | int)) }}
      nodePort: {{ $nodePort.ports.apiGatewayBaseStats.nodePort }}
      {{- end }}
    - name: metrics
      port: {{ default (include "base.apiGatewayBase.metricsPort" .) $nodePort.ports.apiGatewayBaseMetrics.port }}
      targetPort: {{ template "base.apiGatewayBase.metricsPort" . }}
      {{- if and (ge ($nodePort.ports.apiGatewayBaseMetrics.nodePort | int) (30000 | int)) (le ($nodePort.ports.apiGatewayBaseMetrics.nodePort | int) (32767 | int)) }}
      nodePort: {{ $nodePort.ports.apiGatewayBaseMetrics.nodePort }}
      {{- end }}
{{- else if eq .Values.expose.type "loadBalancer" }}
{{- $loadBalancer := .Values.expose.loadBalancer }}
  name: {{ include "base.apiGatewayBase" . }}
  labels:
    {{- include "base.labels" . | indent 4 }}
    app.kubernetes.io/component: api-gateway
  {{- with $loadBalancer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  {{- with $loadBalancer.sourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $loadBalancer.IP }}
  loadBalancerIP: {{ $loadBalancer.IP }}
  {{- end }}
  ports:
    - name: {{ ternary "https" "http" .Values.apiGatewayBase.tls.enabled }}
      port: {{ default (include "base.apiGatewayBase.httpPort" .) $loadBalancer.ports.apiGatewayBaseHttp }}
      targetPort: {{ template "base.apiGatewayBase.httpPort" . }}
    - name: stats
      port: {{ default (include "base.apiGatewayBase.statsPort" .) $loadBalancer.ports.apiGatewayBaseStats }}
      targetPort: {{ template "base.apiGatewayBase.statsPort" . }}
    - name: metrics
      port: {{ default (include "base.apiGatewayBase.metricsPort" .) $loadBalancer.ports.apiGatewayBaseMetrics }}
      targetPort: {{ template "base.apiGatewayBase.metricsPort" . }}
{{- end }}
  selector:
    {{- include "base.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway-base
